### ISSUE TITLE
How to get the same theme as on the screenshot?

### ISSUE THREAD

**Issue by antoyo** [sencer/i3-notifier#4]
Hi.
How to get the same theme as on the screenshot?
Is this a rofi theme?
If so, is there a way to only use it with `i3-notifier`?
Thanks!

**Comment by oldwomanjosiah** [comment]
I was able to configure mine (not well as I only started looking into once I saw your comment but still) by adding another theme in the `rofi-themes` directory in the library install location.

In case you don't already know how to find that you can follow these steps:
- run `pip show i3-notifier | grep Location`  
  This will show you were the `i3notifier` package was installed  
  (the `i3-notifier` script seems to be installed directly into the bin path, whereas the `i3notifier` package was installed in a lib dir)
- `cd` to that location
- cd to `./i3notifier/rofi-theme`
- Add your theme (I found [this collection of themes](https://github.com/davatorium/rofi-themes) useful)
- Change your `theme = "..."` to your new theme name

It does not hot reload the theme for some reason so I had to run 
```bash
# In fish
kill -9 (ps -e | grep i3-notifier | awk '{ print $1 }'); i3-notifier; sleep 1s; notify-send 'Hello World'

# In bash
kill -9 $(ps -e | grep i3-notifier | awk '{ print $1 }'); i3-notifier; sleep 1s; notify-send 'Hello World'
```
In order to test different theme options.

**Comment by sencer** [comment]
Hi,

Sorry I haven't seen this. You can save the notifications with this:

`dbus-send --session --print-reply=literal --dest=org.freedesktop.Notifications /org/freedesktop/Notifications org.freedesktop.Notifications.DumpNotifications`

So just running this should do what you are asking:

```
dbus-send --session --print-reply=literal --dest=org.freedesktop.Notifications /org/freedesktop/Notifications org.freedesktop.Notifications.DumpNotifications

pkill -9 i3-notifier

i3-notifier
```

**Comment by sencer** [comment]
Did you check the config file under the example folder?

Essentially you should have a `$HOME/.config/i3/i3_notifier_config.py` that contains `theme = "widget"` line.

**Comment by antoyo** [comment]
Thanks. It worked!
